import json
import os
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

client = OpenAI(
    api_key=os.getenv("DASHSCOPE_API_KEY", "sk-0fc24c229d174d1b99624a49544b1c7a"),
    base_url="https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
)

SYSTEM_PROMPT = """You are an expert data-extraction model for Indonesian construction documents.
You will receive a single page image from a scanned construction PDF.

Extract every construction item / material specification row visible on this page and return them
as a JSON object with a single key "items" whose value is an array:

{
  "items": [
    {
      "header1": "<top-level section header, e.g. 'Arsitektur', or null if not visible on this page>",
      "header2": "<sub-section header, e.g. 'A. Lantai', or null if not visible on this page>",
      "nama_barang": "<item / material name>",
      "spesifikasi_barang": {
        "spesifikasi_general": "<general specification, dimensions, grade, etc.>",
        "spesifikasi_merek": "<brand / manufacturer, or null if not stated>"
      }
    }
  ]
}

Rules:
- "header1" is the large section title (e.g. "Arsitektur", "Mekanikal", "Elektrikal") that appears
  above a group of items in the table.
- "header2" is the sub-section label (e.g. "A. Lantai", "B. Dinding") that appears directly above
  a smaller group of items within a section.
- If a header is NOT explicitly visible on this page for a given item, set it to null — the caller
  will fill it in from the previous page context (do not invent headers).
- If the page contains no item/material table (e.g. cover page, blank page, text-only page),
  return {"items": []}.
- Do NOT add any commentary, markdown fences, or keys beyond "items".
- Preserve the original language of field values (Indonesian / English) as found in the document.
- Merge multi-line cells into a single string value.
- Respond with valid JSON only."""


def _last_headers_from_items(items: list) -> tuple[str | None, str | None]:
    """
    Scan an item list (in order) and return the last non-null header1 / header2 seen.
    Returns (None, None) if no headers are present.
    """
    last_h1: str | None = None
    last_h2: str | None = None
    for item in items:
        if item.get("header1") is not None:
            last_h1 = item["header1"]
        if item.get("header2") is not None:
            last_h2 = item["header2"]
    return last_h1, last_h2


def extract_page_items(
    page: dict,
    context_prompt: str,
    output_dir: str = "output",
    last_header1: str | None = None,
    last_header2: str | None = None,
) -> tuple[dict, str | None, str | None]:
    """
    Send a single page image to qwen-vl-max and extract construction item rows.

    Saves the result to output/page_{n}.json and also returns it as a dict.
    Skips the API call if the output file already exists (resume support).

    Args:
        page: Dict with keys "page_num" and "base64_image".
        context_prompt: Document-specific guidance generated by Stage 1.
        output_dir: Directory where per-page JSON files are saved.
        last_header1: The last header1 seen on the previous page (for continuity).
        last_header2: The last header2 seen on the previous page (for continuity).

    Returns:
        Tuple of:
          - Parsed dict: {"items": [...]}
          - last_header1 after this page (str or None)
          - last_header2 after this page (str or None)
    """
    os.makedirs(output_dir, exist_ok=True)
    out_path = os.path.join(output_dir, f"page_{page['page_num']}.json")

    # Resume support: skip if already processed
    if os.path.exists(out_path):
        print(f"  [skip] page {page['page_num']} already processed.")
        with open(out_path, "r", encoding="utf-8") as f:
            cached = json.load(f)
        h1, h2 = _last_headers_from_items(cached.get("items", []))
        return cached, h1 or last_header1, h2 or last_header2

    # Build the continuation hint for the model
    header_hint = ""
    if last_header1 or last_header2:
        header_hint = (
            f"\n\nContinuity context from the previous page:"
            f"\n  last header1 = {json.dumps(last_header1, ensure_ascii=False)}"
            f"\n  last header2 = {json.dumps(last_header2, ensure_ascii=False)}"
            "\nFor any items on this page that do NOT have a visible header above them "
            "(i.e. they continue from the previous page), set header1 and header2 to "
            "these values rather than null."
        )

    content = [
        {
            "type": "text",
            "text": (
                f"Document context:\n{context_prompt}{header_hint}\n\n"
                "Now extract all construction items from the page image below. "
                "Return valid JSON only."
            ),
        },
        {
            "type": "image_url",
            "image_url": {
                "url": f"data:image/png;base64,{page['base64_image']}",
            },
        },
    ]

    response = client.chat.completions.create(
        model="qwen-vl-max",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": content},
        ],
        temperature=0.1,
        max_tokens=2048,
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences defensively
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
        raw = raw.strip()

    try:
        result = json.loads(raw)
    except json.JSONDecodeError:
        # Fallback: return empty items rather than crashing the pipeline
        result = {"items": [], "parse_error": raw}

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(result, f, ensure_ascii=False, indent=2)

    h1, h2 = _last_headers_from_items(result.get("items", []))
    return result, h1 or last_header1, h2 or last_header2
